services:

  db:
     image: mysql:8.0
     ports:
       - "3306:3306"
     environment:
       - MYSQL_DATABASE=bdd_sec
       - MYSQL_ROOT_PASSWORD=clave
     restart: always
     
  web:
     build: .
     ports:
       - "8443:8443"
     depends_on:
       - db
     restart: always

